DROP TABLE IF EXISTS users, requests, items, comments, bookings;

create table if not exists users(
    id bigint generated by default as identity not null constraint users_pk primary key,
    name varchar(255) not null,
    email varchar(512) not null constraint uq_users_email unique
);

create table if not exists requests(
    id bigint generated by default as identity not null constraint requests_pk primary key,
    description  varchar(512) not null,
    requestor_id bigint  not null,
    created timestamp not null
);

create table if not exists items(
    id bigint generated by default as identity not null constraint items_pk primary key,
    name varchar(255) not null,
    description varchar(512) not null,
    is_available boolean not null,
    owner_id bigint not null constraint items_users_id_fk references users
        on update cascade on delete cascade,
    request_id bigint constraint items_requests_id_fk references requests
        on update cascade on delete cascade
);

create table if not exists comments(
    id bigint generated by default as identity not null constraint comments_pk primary key,
    text varchar(512) not null,
    item_id bigint  not null constraint comments_items_id_fk references items
            on update cascade on delete cascade,
    author_id bigint  not null constraint comments_users_id_fk references users
            on update cascade on delete cascade
);

create table if not exists bookings(
    id bigint generated by default as identity not null constraint bookings_pk primary key,
    start_time timestamp not null,
    end_time timestamp not null,
    item_id bigint not null constraint bookings_items_id_fk references items
            on update cascade on delete cascade,
    booker_id bigint not null constraint bookings_users_id_fk references users
            on update cascade on delete cascade,
    status varchar(255) not null
);